//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_first_html5.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public cours()
        {
            this.association_etudiant_cours = new HashSet<association_etudiant_cours>();
        }
    
        public int id { get; set; }
        public string cours1 { get; set; }
    
        public virtual ICollection<association_etudiant_cours> association_etudiant_cours { get; set; }
    }
}
