//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_first_html5.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiants
    {
        public Etudiants()
        {
            this.association_etudiant_cours = new HashSet<association_etudiant_cours>();
        }
    
        public int id { get; set; }
        public string date_modif { get; set; }
        public string date { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Age { get; set; }
        public string Phone { get; set; }
        public string Section { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<association_etudiant_cours> association_etudiant_cours { get; set; }
    }
}
