//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_first_html5.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professeurs
    {
        public Professeurs()
        {
            this.association_prof_cours = new HashSet<association_prof_cours>();
        }
    
        public int id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Phone { get; set; }
        public int Age { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<association_prof_cours> association_prof_cours { get; set; }
    }
}
