//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lycee_duprat_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cours
    {
        public cours()
        {
            this.etudiant_cours = new HashSet<etudiant_cours>();
            this.professeur_cours = new HashSet<professeur_cours>();
        }
    
        public int Id { get; set; }
        public Nullable<int> durée { get; set; }
        public string Nom_du_cours { get; set; }
    
        public virtual ICollection<etudiant_cours> etudiant_cours { get; set; }
        public virtual ICollection<professeur_cours> professeur_cours { get; set; }
    }
}
