//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lycee_duprat_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class etudiants
    {
        public etudiants()
        {
            this.etudiant_cours = new HashSet<etudiant_cours>();
        }
    
        public int ld { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
    
        public virtual ICollection<etudiant_cours> etudiant_cours { get; set; }
    }
}
