//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lycee_duprat_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class professeur_cours
    {
        public int professeur { get; set; }
        public int cours { get; set; }
        public string champ_pour_genere_table { get; set; }
    
        public virtual cours cours1 { get; set; }
        public virtual professeurs professeurs { get; set; }
    }
}
